name: "Home For Sale"
description: "House for sale in New Salem, Nova Scotia, Canada"
url: "http://localhost:4000"
baseurl: /buy-my-house
cdn: dkwbecc2zstv9.cloudfront.net

permalink: pretty
layout: default
timezone: America/Halifax

navigation:
- text: HOME
  title: Home
  url: /buy-my-house/
- text: Attractions
  title: attractions
  url: /buy-my-house/attractions/
- text: Map
  title: map
  url: /buy-my-house/map/   
- text: CONTACT
  title: Contact Me
  url: /buy-my-house/contact_me/
