name: "Home For Sale"
description: "House for sale in New Salem, Nova Scotia, Cananda"
url: "http://localhost:4000"
baseurl: /mcleveland.ca

permalink: pretty
layout: default
timezone: America/Halifax

navigation:
- text: HOME
  title: Home
  url: /
- text: Attractions
  title: attractions
  url: /attractions/
- text: Map
  title: map
  url: /map/   
- text: CONTACT
  title: Contact Me
  url: /contact_me/
